"""initial_migration

Revision ID: 80d20ea9e779
Revises: 
Create Date: 2026-05-30 11:56:39.827800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d20ea9e779'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demandes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('canal', sa.String(length=50), nullable=True),
    sa.Column('langue', sa.String(length=5), nullable=True),
    sa.Column('langue_confidence', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('routed_priority', sa.String(length=30), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demandes')
    # ### end Alembic commands ###
